language: node_js
node_js:
  - "8.9.3"
cache:
  directories:
  - node_modules
script:
  - npm run build
after_success:
  - mv CNAME build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify?secret=gnomaasiasummit2019
